import type { Product } from '../types'

/**
 * Каталог. Добавить товар = добавить объект в массив.
 * popular: true — товар попадёт в блок «Берут чаще всего» на главной.
 */
export const PRODUCTS: Product[] = [
  {
    id: 'pubg-325',
    game: 'PUBG Mobile',
    title: '325 UC',
    price: 390,
    requires: 'ID аккаунта',
    keywords: ['пубг', 'ук', 'uc'],
  },
  {
    id: 'pubg-660',
    game: 'PUBG Mobile',
    title: '660 UC',
    price: 760,
    requires: 'ID аккаунта',
    note: 'Хватает на Royal Pass Plus',
    popular: true,
    keywords: ['пубг', 'ук', 'uc'],
  },
  {
    id: 'pubg-1800',
    game: 'PUBG Mobile',
    title: '1800 UC',
    price: 1990,
    requires: 'ID аккаунта',
    keywords: ['пубг', 'ук', 'uc'],
  },
  {
    id: 'pubg-rp',
    game: 'PUBG Mobile',
    title: 'Royal Pass A1',
    price: 890,
    requires: 'ID аккаунта',
    note: 'Обычный или Plus — уточним в переписке',
    keywords: ['пубг', 'роял пасс', 'боевой пропуск', 'rp'],
  },
  {
    id: 'standoff-gold-500',
    game: 'Standoff 2',
    title: '500 золота',
    price: 420,
    requires: 'Ник и ID',
    keywords: ['стандофф', 'стандов', 'gold'],
  },
  {
    id: 'standoff-gold-1200',
    game: 'Standoff 2',
    title: '1200 золота',
    price: 950,
    requires: 'Ник и ID',
    popular: true,
    keywords: ['стандофф', 'стандов', 'gold'],
  },
  {
    id: 'standoff-pass',
    game: 'Standoff 2',
    title: 'Боевой пропуск',
    price: 790,
    requires: 'Ник и ID',
    note: 'Текущий сезон',
    keywords: ['стандофф', 'battle pass', 'бп'],
  },
  {
    id: 'brawl-gems-170',
    game: 'Brawl Stars',
    title: '170 гемов',
    price: 690,
    requires: 'Тег игрока',
    keywords: ['бравл', 'гемы', 'gems'],
  },
  {
    id: 'brawl-gems-360',
    game: 'Brawl Stars',
    title: '360 гемов',
    price: 1290,
    requires: 'Тег игрока',
    keywords: ['бравл', 'гемы', 'gems'],
  },
  {
    id: 'brawl-pass',
    game: 'Brawl Stars',
    title: 'Brawl Pass',
    price: 650,
    requires: 'Тег игрока',
    popular: true,
    keywords: ['бравл', 'пропуск', 'пасс'],
  },
  {
    id: 'clash-gems-500',
    game: 'Clash of Clans',
    title: '500 кристаллов',
    price: 620,
    requires: 'Тег игрока',
    keywords: ['клеш', 'клэш', 'кристаллы', 'gems'],
  },
  {
    id: 'roblox-800',
    game: 'Roblox',
    title: '800 Robux',
    price: 780,
    requires: 'Ник в игре',
    note: 'Зачисляем через геймпасс',
    popular: true,
    keywords: ['роблокс', 'робуксы', 'robux'],
  },
  {
    id: 'roblox-1700',
    game: 'Roblox',
    title: '1700 Robux',
    price: 1550,
    requires: 'Ник в игре',
    keywords: ['роблокс', 'робуксы', 'robux'],
  },
  {
    id: 'genshin-980',
    game: 'Genshin Impact',
    title: '980 кристаллов',
    price: 1190,
    requires: 'UID и сервер',
    keywords: ['геншин', 'генша', 'кристаллы', 'примогемы'],
  },
  {
    id: 'genshin-bp',
    game: 'Genshin Impact',
    title: 'Благословение полой луны',
    price: 420,
    requires: 'UID и сервер',
    keywords: ['геншин', 'луна', 'подписка'],
  },
  {
    id: 'freefire-520',
    game: 'Free Fire',
    title: '520 алмазов',
    price: 540,
    requires: 'ID аккаунта',
    keywords: ['фри фаер', 'алмазы', 'diamonds'],
  },
  {
    id: 'mlbb-500',
    game: 'Mobile Legends',
    title: '500 алмазов',
    price: 690,
    requires: 'ID и сервер',
    keywords: ['мобайл легенд', 'млбб', 'алмазы'],
  },
  {
    id: 'steam-500',
    game: 'Steam',
    title: 'Пополнение на 500 ₽',
    price: 590,
    requires: 'Логин Steam',
    note: 'Комиссия уже в цене',
    popular: true,
    keywords: ['стим', 'кошелёк', 'баланс'],
  },
  {
    id: 'steam-1000',
    game: 'Steam',
    title: 'Пополнение на 1000 ₽',
    price: 1150,
    requires: 'Логин Steam',
    keywords: ['стим', 'кошелёк', 'баланс'],
  },
  {
    id: 'tg-premium-3',
    game: 'Telegram',
    title: 'Premium на 3 месяца',
    price: 990,
    requires: 'Ник получателя',
    keywords: ['телеграм', 'премиум', 'premium'],
  },
  {
    id: 'tg-stars-500',
    game: 'Telegram',
    title: '500 звёзд',
    price: 850,
    requires: 'Ник получателя',
    keywords: ['телеграм', 'звезды', 'stars'],
  },
  {
    id: 'cs2-key',
    game: 'CS2',
    title: 'Ключ от кейса',
    price: 320,
    requires: 'Ссылка на обмен',
    keywords: ['кс2', 'ксго', 'key', 'кейс'],
  },
]

/**
 * Товары для блока «Берут чаще всего» на главной.
 * Берём всё, что помечено popular: true, и обрезаем до нужного количества.
 */
export function topPopular(products: Product[], limit = 5): Product[] {
  return products.filter((p) => p.popular).slice(0, limit)
}
